### ISSUE TITLE
publish vim /  nvim plugin package ?

### ISSUE THREAD

**Issue by rfyiamcool** [fzdwx/popup-translation#1]

**Comment by fzdwx** [comment]
你有什么建议吗？

**Comment by rfyiamcool** [comment]
看到 readme 有个 vim map 映射了。

**Comment by fzdwx** [comment]
> 看到 readme 有个 vim map 映射了。

哈哈，那个比较简陋，感觉获取的词不准确，想做成获取选择文本的类型

**Comment by xp12047** [comment]
这个该怎么安装到neovim？复制那个新建lua文件然后就可以了吗？看起来很好玩。

**Comment by fzdwx** [comment]
> 这个该怎么安装到neovim？复制那段代码新建lua文件然后就可以了吗？看起来很好玩。

1. 先安装 `cargo install popup-translation`
2. 在 init.lua 中添加就可以了

https://github.com/fzdwx/nvim/blob/main/lua/config/keymaps.lua#L25

**Comment by xp12047** [comment]
> > 这个应该怎么安装到neovim？复制那段代码新建lua文件然后就可以了吗？看起来很好玩。
> 
> 1. 先安装`cargo install popup-translation`
> 2. 在init.lua中添加就可以了
> 
> https://github.com/fzdwx/nvim/blob/main/lua/config/keymaps.lua#L25

好，谢谢

**Comment by fzdwx** [comment]
是的

**Comment by xp12047** [comment]
> 是的

好，谢谢
