### ISSUE TITLE
为 api 类型的翻译器添加一个输入框，可以一直翻译

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/popup-translation#10]
目前已经通过 [自定义协议](https://github.com/fzdwx/popup-translation/blob/main/src/main.rs#L118) 实现里的 icon 的获取: [image](https://user-images.githubusercontent.com/65269574/220928754-c6b7b1ea-b53c-4aae-a6e6-201af6f50b49.png).

同理, 可以在为这个网页添加一个 input 输入框以及一个按钮, 
同这个按钮发送请求 `wry://xxx` 然后请求处理器调用 api 进行翻译, 最后显示到页面上

最终效果类似:

![image](https://user-images.githubusercontent.com/65269574/220929423-d44c5986-a023-4dbd-84a2-8ff07489b085.png)

**Comment by fzdwx** [comment]
目前卡在 html 页面发送请求后，rust 能返回数据，但是 html 页面上接收不到

**Comment by Chanyon** [comment]
> 目前卡在 html 页面发送请求后，rust 能返回数据，但是 html 页面上接收不到

我在windows试了一下，获取不到rust返回的数据。

**Comment by fzdwx** [comment]
把webview的debug页面打开看，反键点开。

我最新代码好像把按钮隐藏了，你可以打开，然后点击发请求，那个 response preview 是可以看到有数据的

Chengyun ***@***.***> 于 2023年2月25日周六 下午5:42写道：

**Comment by Chanyon** [comment]
> 把webview的debug页面打开看，反键点开。 我最新代码好像把按钮隐藏了，你可以打开，然后点击发请求，那个 response preview 是可以看到有数据的 

图标地址: `https://wry.dev/icon`, 不能加载资源
获取输入框value后request 错误
![image](https://user-images.githubusercontent.com/40350332/221353012-6ea0c364-9a3f-46b9-ab80-ca80039c99b9.png)

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/221353336-e3930b7f-1d08-494b-8577-cf612751852a.png)

这个你获取不到吗？

**Comment by fzdwx** [comment]
`header("Origin", "http://localhost/")` 可能是这里有问题

**Comment by Chanyon** [comment]
> ![image](https://user-images.githubusercontent.com/65269574/221353336-e3930b7f-1d08-494b-8577-cf612751852a.png)
> 
> 这个你获取不到吗？

获取不到icon

**Comment by fzdwx** [comment]
看来各个平台的 webview 都有一些各自的问题
