### ISSUE TITLE
能否为不懂编程的人提供一个可以使用的教程？

### ISSUE THREAD

**Issue by zhl111** [fzdwx/popup-translation#11]
想用却不知如何下手，非常抱歉......

**Comment by fzdwx** [comment]
你是啥系统的？ 我打个包给你

---

1. 关于 windows 没有`WebView2 Loader.dll` 可以参考 https://www.dll-files.com/webview2loader.dll.html ( 大概就是下载这个 dll 然后放到与 exe 同目录下就可以了)

**Comment by zhl111** [comment]
win11

**Comment by fzdwx** [comment]
> win11

hello, 我用 action 生成了一个 https://github.com/fzdwx/popup-translation/releases/tag/preview 你可以试试

**Comment by zhl111** [comment]
非常感谢您

目前提示“系统错误 由于找不到WebView2 Loader.dl,无法继续执行代码。重新安装程序可能会解决此问题。”
我在用WinThruster修复之后，继续补充回复，

**Comment by fzdwx** [comment]
可以看这个 https://tauri.app/zh-cn/v1/guides/getting-started/prerequisites/#2-webview2

https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/221185116-1fdcc9b4-f380-4af5-b3fb-5dad64009d6b.png)
看起来我是安装了的，但我双击fanyi.exe还是上述提示
![image](https://user-images.githubusercontent.com/29135984/221185575-531c2d27-0285-447c-9b52-182c55534f3b.png)

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/221187194-d0cf429f-2bdd-40d5-8a17-ac07abe97c51.png)

你试试这个看看

**Comment by zhl111** [comment]
都试过了，一样的

**Comment by fzdwx** [comment]
那没办法了，只能在你的电脑上面自己编译了，我的电脑是 linux 的。

需要安装 rust.

https://tauri.app/zh-cn/v1/guides/getting-started/prerequisites/#3-rust

**Comment by zhl111** [comment]
出现了点转机，我找到一个版本的dll，可以打开cmd界面了，但无法输入任何东西
![image](https://user-images.githubusercontent.com/29135984/221199808-7801f188-abaf-4786-8b41-d6512c1f131b.png)

**Comment by fzdwx** [comment]
ok,这个已经启动了， 使用 alt+shfit+c 翻译复制的文本 或者 在 cmd 中运行 `fanyi.exe hello`

**Comment by zhl111** [comment]
还有一点问题：
![image](https://user-images.githubusercontent.com/29135984/221205294-53138d56-c51a-49fd-b4f7-d3aaa405c9b6.png)

**Comment by fzdwx** [comment]
./fanyi.exe 试试

**Comment by zhl111** [comment]
又有了一些进展，只是不知如何取词，我试了`alt+s`和`alt+shift+c`都不行，这个弹窗我也不会关闭
![image](https://user-images.githubusercontent.com/29135984/221208323-0d9f1507-c236-4d4e-9d86-c068dea872dc.png)

**Comment by fzdwx** [comment]
OK, 我现在打开了标题栏，你等下到 release 页面重新下载，就有关闭按钮了。

alt+shift+c 是读取粘贴板，你多看看 README，也可以运行 `fanyi.exe --help`

**Comment by zhl111** [comment]
非常感谢，已经可以正常使用了。关于dll文件缺失的问题，可以从这个网页得到解决：https://www.dll-files.com/download/498c7875a2890b90eec37f02c7ac3395/webview2loader.dll.html?c=U09FSU9yaWZWMkd2WnBsK2d2S2dXdz09

一个小问题：cmd设置的快捷键如果关闭cmd之后，这个自定的快捷键就失效了吧？我测试的结果是这样的，每次都要操作一遍吗？

**Comment by fzdwx** [comment]
是的
