### ISSUE TITLE
运行无弹窗，结束程序时报错

### ISSUE THREAD

**Issue by xiaobaoor** [fzdwx/popup-translation#12]
1. 使用fanyi 命令运行，显示成功启动，但快捷键无法调出弹窗，功能无法使用
2. 用fanyi hello测试运行，但没有弹窗，
而后结束运行时出现如下报错：
[0227/084219.306:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
本地环境是WIN10，用的GNU的工具链打包

**Comment by fzdwx** [comment]
不知道有没有 webview2，以下两个链接供参考

1. https://tauri.app/zh-cn/v1/guides/getting-started/prerequisites
2. https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

--- 

或者试试其他的平台？ `-p` 指定

**Comment by xiaobaoor** [comment]
webview2已经成功安装过，启动后能看webview2进程。但还是没有弹窗，`-p`也没用

**Comment by fzdwx** [comment]
-p 后面要跟参数

**Comment by xiaobaoor** [comment]
我知道，youdao和bing的都试过，

**Comment by fzdwx** [comment]
google试试？
