### ISSUE TITLE
后台模式bug

### ISSUE THREAD

**Issue by Chanyon** [fzdwx/popup-translation#2]
bug: 后台模式,使用快捷键不能弹出翻译显示界面。
操作系统: win10

**Comment by fzdwx** [comment]
没有 windows 操作系统，手上只有 linux

你可以描述下大概是什么 bug？ 默认快捷键是 `ctrl+alt+c` https://github.com/fzdwx/popup-translation/blob/main/src/main.rs#L65

**Comment by Chanyon** [comment]
简单描述：启动powershell，输入fanyi，选中要翻译的文字，使用ctrl+alt+c

**Comment by fzdwx** [comment]
要复制，是从粘贴板上读取的

---

目前还不知道怎么支持 读取选中文本 的功能

**Comment by Chanyon** [comment]
复制快捷键翻译没问题。

**Comment by Chanyon** [comment]
[Windows下获取鼠标当前选中文字]
https://blog.xenori.com/2021/05/get-selected-text-in-windows/

**Comment by fzdwx** [comment]
老哥，要不你帮忙试着改改 : )

**Comment by fzdwx** [comment]
linux 上我已经实现了
