### ISSUE TITLE
支持选择文本后通过快捷键进行翻译

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/popup-translation#3]
- [x] 1.Windows 
		 -  目前是唤起窗口后，模拟了一次 `ctrl+c` 的操作(by  @Chanyon) 如果有个更好的方案欢迎 PR
		 - #4
- [x] 2.Macos
- [x] 3.Linux - x11

_Originally posted by @Chanyon in https://github.com/fzdwx/popup-translation/issues/2#issuecomment-1427359668_

**Comment by Chanyon** [comment]
这个库enigo支持跨平台，在Macos 也能模拟复制操作。

**Comment by fzdwx** [comment]
好的
